version: '3.9'

services:

  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    cap_add:
      - SYS_NICE
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: super_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    restart: on-failure
    volumes:
      - ./deployment/mysql/config.sql:/docker-entrypoint-initdb.d/data.sql
    # networks:
      # - super_network

  activemq:
    image: rmohr/activemq:5.15.9
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
      - "61613:61613"
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    # networks:
    #   - super_network

  composer:
    build:
      context: ../
      dockerfile: ./deployment/composer/Dockerfile
    container_name: composer
    ports:
      - "4002:4002"
    depends_on:
      - mysql
      - activemq
    # networks:
      # - super_network
    restart: on-failure
    env_file: ../docker-compose.env
    environment:
      - PYTHONPATH=/home/app


networks:
  super_network: {}
